config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :products do
    member do
      put 'like' => 'products#like'
    end
  end

  Rails.application.routes.draw do
    devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions',
      omniauth_callbacks: 'users/omniauth_callbacks'
    }
  end


  root to: "main#index"

  
  delete "users/:id", to: "users#destroy", as: "destroy_user"

  get "users_list", to: "main#users"
  get "product_list", to: "main#products"
  get "dashboard", to: "main#dashboard"
  get "/edit_role/:user_id", to: "main#edit_role", as: "edit_role"
  post "/edit_role/:user_id", to: "main#edit_role", as: "update_role"

  resource :cart, only: [:show, :update]
  delete 'cart/:order_id/remove_product/:product_id/', to: 'carts#remove_product', as: 'remove-product'
  get "cart/:order_id/mercado-pago", to: "carts#mercadopago", as: "mercado-pago"
  get "payment-info", to: "carts#payment_info"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  #before_action :set_order, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index ]

  # GET /orders or /orders.json
  def index
    
  end
  
	def dashboard
    if current_user.has_role?(:admin)
      @products_count = Product.all.count
      @completed_orders_count = Order.where(state: 2).count
     ### charts
      @monthly_completed_orders = Order.where(state: 2).group_by_month(:created_at).count
      @products_by_owner = Product.joins(:user).group("users.name").count
      a = Product.joins(:orders).where(orders: {state: 2}).group(:title).count
      @best_products = (a.sort_by(&:last).reverse.first(10).to_h)

    else 
      @products_count = Product.where(user_id: current_user.id).count
      @completed_orders_count = Order.where(state: 2, user_id: current_user.id).count
      ##charts
      @monthly_completed_orders = Order.joins(:products).where(orders: {state: 2}, products: {user_id: current_user.id}).group_by_month(:created_at).count
      @products_by_stock = Product.where(user_id: current_user.id).group(:title).maximum(:stock)
      a = Product.joins(:orders).where(orders: {state: 2}, products: {user_id: current_user.id}).group(:title).count
      @best_products = (a.sort_by(&:last).reverse.first(10).to_h)
    end
    @users_count = User.all.count
  end

  def users
    @users = User.all.joins(:roles).order(role_id: :asc).page(params[:page]).per(20)
  end

  def products
    if current_user.has_role?(:admin)
      @products = Product.order(stock: :desc).page(params[:page]).per(20)
      @q = Product.ransack(params[:q])
      @products = @q.result(distinct: true).page(params[:page]).per(20)

    elsif current_user.has_role?(:owner)
      @products = Product.where(user_id: current_user.id).order(stock: :desc).page(params[:page]).per(20)
      @q = Product.includes(:user).where(user_id: current_user.id).ransack(params[:q])
      @products = @q.result(distinct: true).page(params[:page]).per(20)

    else
      @products = Product.joins(:orders).where(orders: {user_id: current_user.id, state: 2}).page(params[:page]).per(20)
      @q = Product.includes(:orders).where(orders: {user_id: current_user.id, state: 2}).ransack(params[:q])
      @products = @q.result(distinct: true).page(params[:page]).per(20)
    end
  end

  def edit_role
    @user = User.find(params[:user_id])
    @roles = Role.all
    if params[:admin] == "1"
      @user.add_role(:admin)
    elsif params[:admin] == "0"
      @user.remove_role(:admin)
    end

    if params[:owner] == "1"
      @user.grant(:owner)
    elsif params[:owner] == "0"
      @user.remove_role(:owner)
    end

    if params[:normaluser] == "1"
      @user.grant(:normaluser)
    elsif params[:normaluser] == "0"
      @user.remove_role(:normaluser)
    end

  end

end

app/views/main/_charts.html.erb
<h2 class="section-heading my-5">
  <span class="section-heading-upper">Best Sellers in Products</span>
</h2>
<%= bar_chart @best_products, xtitle: "Sales volume", ytitle: "Product", colors: ["#825f58"] %>
<% if current_user.has_role?(:admin) %>
  <h2 class="section-heading my-5">
    <span class="section-heading-upper">Products per Seller</span>
  </h2>
  <%= column_chart @products_by_owner, xtitle: "Seller", ytitle: "# Product listed", colors: ["#825f58"] %>
<% else %>
  <h2 class="section-heading my-5">
    <span class="section-heading-upper">Products per Stock</span>
  </h2>
  <%= column_chart @products_by_stock, xtitle: "Product", ytitle: "Available Stock", colors: ["#825f58"],  stacked: true %>
<% end %>
<h2 class="section-heading my-5">
  <span class="section-heading-upper">Monthly Orders</span>
</h2>
<%= line_chart @monthly_completed_orders, ytitle: "# Orders", colors: ["#825f58"] %>

app/views/main/dashboard.html.erb
<section class="page-section cta">
  <div class="container">
    <div class="row">
      <div class="col-xl-12 mx-auto">
        <div class="cta-inner bg-faded text-center rounded">
    
            <h2 class="section-heading mb-5">
              <span class="section-heading-lower">Dashboard</span>
            </h2>
            <div class="row justify-content-sm-center">
              <div class="col-sm-3">
                <div class="card">
                  <div class="card-body">
                    <h1 class="card-title">
                      <% if current_user.has_role? :admin %>
                        <%= link_to @users_count, users_list_path %>
                      <% else %>
                        <%= @users_count %>
                      <% end %>
                    </h1>
                    <p class="card-text">Registered users.</p>
                  </div>
                </div>
              </div>
              <div class="col-sm-3">
                <div class="card">
                  <div class="card-body">
                    <h1 class="card-title"><%= link_to @completed_orders_count, orders_path %></h1>
                    <p class="card-text">Completed orders.</p>
                  </div>
                </div>
              </div>
              <div class="col-sm-3">
                <div class="card">
                  <div class="card-body">
                    <h1 class="card-title"><%= link_to @products_count, product_list_path %></h1>
                    <p class="card-text">Listed products.</p>
                  </div>
                </div>
              </div>
            </div>
         
        
            <h2 class="section-heading my-5">
              <span class="section-heading-lower">Chart Overview</span>
            </h2>
            <%= render "main/charts" %>
          
        </div>
      </div>
    </div>
  </div>
</section>

app/views/main/edit_role.html.erb
<section class="page-section cta">
  <div class="container">
    <div class="row">
      <div class="col-xl-12 mx-auto">
        <div class="cta-inner bg-faded text-center rounded">
          <h1>Edit Roles</h1>
          <h5><strong>User Name:</strong> <%= @user.name %></h5><br>

          <%= form_for :role do |f| %>
            <div class="field">
              <%= hidden_field_tag "user[role_ids][]", nil %>
              <%= f.label(:admin) do %>
                Admin
                <%= hidden_field_tag(:admin, 0) %>
                <%= check_box_tag(:admin, 1, @user.has_role?(:admin)) %>
              <% end %>
              <br>
              <%= f.label(:owner) do %>
                Owner
                <%= hidden_field_tag(:owner, 0) %>
                <%= check_box_tag(:owner, 1, @user.has_role?(:owner)) %>
              <% end %>
              <br>
              <%= f.label(:normaluser) do %>
                Normal user
                <%= hidden_field_tag(:normaluser, 0) %>
                <%= check_box_tag(:normaluser, 1, @user.has_role?(:normaluser)) %>
              <% end %>
              <br>
            </div>
            <div class="actions">
              <%= f.submit %>
            </div>
          <% end %>
          </br>
          <%= link_to "Back to user list", users_list_path %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/main/index.html.erb
<section class="page-section clearfix">
  <div class="container">
    <div class="intro">
      <%= image_tag asset_path("pexels-markus-spiske-2956143.jpg"), class: "intro-img img-fluid mb-3 mb-lg-0 rounded", alt: "intro image" %>
      <div class="intro-text left-0 text-center bg-faded p-5 rounded">
        <h2 class="section-heading mb-4">
          <span class="section-heading-upper">Fresh Music</span>
          <span class="section-heading-lower">Worth Checking</span>
        </h2>
        <p class="mb-3"><%= Faker::Lorem.sentence(word_count: 30) %></p>
        <div class="intro-button mx-auto">
          <%= link_to "Sign up Today!", new_user_registration_path, class: "btn btn-primary btn-xl" %>
      </div>
    </div>
  </div>
</section>
<section class="page-section cta">
  <div class="container">
    <div class="row">
      <div class="col-xl-9 mx-auto">
        <div class="cta-inner bg-faded text-center rounded">
          <h2 class="section-heading mb-4">
            <span class="section-heading-upper">Our Promise</span>
            <span class="section-heading-lower">To You</span>
          </h2>
          <p class="mb-0"><%= Faker::Lorem.sentence(word_count: 50) %></p>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/main/products.html.erb
<section class="page-section cta">
  <div class="container">
    <div class="row">
      <div class="col-xl-12 mx-auto">
        <div class="cta-inner bg-faded text-center rounded">
 

          <% if current_user.has_role?(:owner) || current_user.has_role?(:admin) %>
            <div class="d-grid gap-2 d-md-flex justify-content-md-end mt-2">
              <%= link_to new_product_path do %>
                <button class="btn btn-outline-dark btn-sm" type="button">Add more products</button>
              <% end %>
              <button class="btn btn-outline-primary btn-sm" type="button">
                <%= sort_link @q, :unit_price do %>
                  Sort by Price
                <% end %>
              </button>
              <button class="btn btn-outline-primary btn-sm" type="button">
                <%= sort_link @q, :stock do %>
                  Sort by Stock
                <% end %>
              </button>
            </div>
          <% end %>
          
          <div class="container">
            <div class="row">
              <div class="col-xl-9 col-lg-10 mx-auto">
                <h1><%= current_user.has_role?(:normaluser) ? "Bought Products" : "Listed Products" %></h1>
                
                <table class="mx-auto">
                  <thead>
                    <tr>
                      <th>Owner</th>
                      <th>Product</th>
                      <th>Description</th>
                      <th>Unit price</th>
                      <th><%= current_user.has_role?(:normaluser) ? "Buy Again" : "Available Stock" %></th>
                    </tr>
                  </thead>
                
                  <tbody>
                    <% @products.each do |product| %>
                      <tr>
                        <td><%= product.user.name %></td>
                        <td><%= link_to product.title, product %></td>
                        <td><%= product.description %></td>
                        <td><%= number_to_currency(product.unit_price, strip_insignificant_zeros: true, delimiter: ".") %></td>
                        <td>
                          <% if current_user.has_role?(:normaluser) %>
                            <% if product.stock > 0  %>
                              <%= form_for :cart, url: cart_path, method: :put do |f| %>
                                <%= f.hidden_field :product_id, value: product.id %>
                                <%= f.hidden_field :quantity, value: 1 %>
                                <%= f.submit "Add to cart", class: "btn btn-outline-dark mt-auto btn-sm" %>
                              <% end %>
                            <% else %>
                              <%= button_tag "Out of Stock", disabled: true, class: "btn btn-outline-dark mt-auto btn-sm"%>
                            <% end %>
                          <% else %>
                            <%= product.stock %>
                          <% end %>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
                <div class="pagination justify-content-center pagination-sm">
                  <h5 class="m-4 text-center p-3">
                    <span class="address" style="letter-spacing: 2px"><%= paginate @products %></span>
                  </h5>
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</section>

app/views/main/users.html.erb
<section class="page-section cta">
  <div class="container">
    <div class="row">
      <div class="col-xl-12 mx-auto">
        <div class="cta-inner bg-faded text-center rounded">

          <div class="container">
            <div class="row">
              <div class="col-xl-9 col-lg-10 mx-auto">
                <h1>Users</h1>

                <table>
                  <thead>
                    <tr>
                      <th>Name</th>
                      <th>Email</th>
                      <th>Country</th>
                      <th>Completed orders</th>
                      <th>Posted products</th>
                      <th>Role</th>
                      <th colspan="2"></th>
                    </tr>
                  </thead>

                  <tbody>
                    <% @users.each do |user| %>
                      <tr>
                        <td><%= user.name %></td>
                        <td><%= user.email %></td>
                        <td><%= user.country %></td>
                        <td><%= user.orders.where(state: 2).count %></td>
                        <% if user.has_role?(:normaluser) %>
                          <td>Not allowed to add products</td>
                        <% else %>
                          <td><%= user.products.count %></td>
                        <% end %>
                        <td><%= user.roles.pluck(:name).join("; ") %></td>
                        <td>
                          <%= link_to "Edit role", edit_role_path(user) %>
                        </td>
                        <td><%= link_to 'Destroy user', destroy_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
                <div class="pagination justify-content-center pagination-sm">
                  <h5 class="m-4 text-center p-3">
                    <span class="address" style="letter-spacing: 2px"><%= paginate @users %></span>
                  </h5>
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</section>