config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :products do
    member do
      put 'like' => 'products#like'
    end
  end

  Rails.application.routes.draw do
    devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions',
      omniauth_callbacks: 'users/omniauth_callbacks'
    }
  end


  root to: "main#index"

  
  delete "users/:id", to: "users#destroy", as: "destroy_user"

  get "users_list", to: "main#users"
  get "product_list", to: "main#products"
  get "dashboard", to: "main#dashboard"
  get "/edit_role/:user_id", to: "main#edit_role", as: "edit_role"
  post "/edit_role/:user_id", to: "main#edit_role", as: "update_role"

  resource :cart, only: [:show, :update]
  delete 'cart/:order_id/remove_product/:product_id/', to: 'carts#remove_product', as: 'remove-product'
  get "cart/:order_id/mercado-pago", to: "carts#mercadopago", as: "mercado-pago"
  get "payment-info", to: "carts#payment_info"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
  <div class="container">
    <%= link_to 'Bandsells', root_path, class: "navbar-brand text-uppercase fw-bold d-lg-none" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mx-auto">
        <% if user_signed_in? %>
          <li class="nav-item px-lg-4 px-lg-4">
              <% if current_user.has_role?(:normaluser) %>
                <%= link_to 'Products',  product_list_path, class: "nav-link text-uppercase" %>
              <% else %>
                <%= link_to 'Home', dashboard_path, class: "nav-link text-uppercase" %>
              <% end %>
          </li>
          <li class="nav-item px-lg-4 px-lg-4">
            <%= link_to 'Goods & Merch', products_path, class: "nav-link text-uppercase" %>
          </li>
          <li class="nav-item px-lg-4">
            <%= link_to 'Orders', orders_path, class: "nav-link text-uppercase" %>
          </li>
          <li class="nav-item dropdown">
            <span class="nav-link dropdown-toggle text-uppercase" id="userOptions" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Logged in as <%= current_user.name %>
            </span>
            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="userOptions">
              <li>
                <%= link_to 'Edit profile', edit_user_registration_path, class: "dropdown-item" %> 
              </li>
              <li>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </li>
            </ul>
          </li>
         <% else %>
          <li class="nav-item px-lg-4">
            <%= link_to 'Home', root_path, class: "nav-link text-uppercase" %>
          </li>
          <li class="nav-item px-lg-4">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link text-uppercase" %>
          </li>
          <li class="nav-item px-lg-4">
            <%= link_to "Login", new_user_session_path, class: "nav-link text-uppercase" %>
          </li>
        <% end %>
      </ul>
      <div class="d-flex">
        <%= link_to cart_path, class:"nav-item px-lg-4" do %>
          <button type="button" class="btn btn-primary position-relative">
            <span><i class="fa fa-shopping-cart"></i></span>
            Cart
            <% if user_signed_in? && existing_order.present? %>
              <% unless existing_order.quantity == 0 || existing_order.quantity == nil %>
                <span class="position-absolute top-0 start-100 translate-middle badge mark text-dark ms-1 rounded-pill">                  
                  <%= existing_order.quantity %>
                  <span class="visually-hidden">products</span>
                </span>
              <% end %>
            <% end %>
          </button>
        <% end %>          
      </div>
    </div>
  </div>
</nav>

app/views/shared/_productlist.html.erb
<div class="container px-4 px-lg-5 mt-5">
  <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
    <% @products.each do |product| %>
      <div class="col mb-5">
        <div class="card h-100">
          <!-- Product image-->
          <% if product.image.attached? %>
            <%= link_to product do %>
              <%= image_tag product.image, class: "card-img-top", alt: "#{product.title}" %>
            <% end  %>
				  <% end %>
          <!-- Product details-->
          <div class="card-body p-4">
            <div class="text-center">
              <!-- Product name-->
              <h5 class="fw-bolder"><%= product.title %></h5>
              <!-- Product reviews-->
              <div class="d-flex justify-content-center small text-warning mb-2">
                <div id="like-count"><%= render 'products/likes', product: product %></div>
              </div>
              <!-- Product price-->
              <%= number_to_currency(product.unit_price, strip_insignificant_zeros: true, delimiter: ".") %>
            </div>
          </div>
          <!-- Product actions-->
          <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
            <div class="text-center">
              <% if product.stock > 0  %>
                <%= form_for :cart, url: cart_path, method: :put do |f| %>
                  <%= f.hidden_field :product_id, value: product.id %>
                  <%= f.hidden_field :quantity, value: 1 %>
                  <%= f.submit "Add to cart", class: "btn btn-outline-dark mt-auto" %>
                <% end %>
              <% else %>
                <%= button_tag "Out of Stock", disabled: true, class: "btn btn-outline-dark mt-auto"%>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>



  