config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :products do
    member do
      put 'like' => 'products#like'
    end
  end

  Rails.application.routes.draw do
    devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions',
      omniauth_callbacks: 'users/omniauth_callbacks'
    }
  end


  root to: "main#index"

  
  delete "users/:id", to: "users#destroy", as: "destroy_user"

  get "users_list", to: "main#users"
  get "product_list", to: "main#products"
  get "dashboard", to: "main#dashboard"
  get "/edit_role/:user_id", to: "main#edit_role", as: "edit_role"
  post "/edit_role/:user_id", to: "main#edit_role", as: "update_role"

  resource :cart, only: [:show, :update]
  delete 'cart/:order_id/remove_product/:product_id/', to: 'carts#remove_product', as: 'remove-product'
  get "cart/:order_id/mercado-pago", to: "carts#mercadopago", as: "mercado-pago"
  get "payment-info", to: "carts#payment_info"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/cart_controller.rb
class CartsController < ApplicationController
  def show
    @product_orders = current_order.product_orders
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def update
    product = params[:cart][:product_id]
    quantity = params[:cart][:quantity]

    current_order.add_product(product, quantity)
    current_order.counting_products
    redirect_to cart_url, notice: "Product added successfuly"
  end

  def show
    @order = current_order
  end

  def remove_product
      order = Order.find(params[:order_id])
      product = Product.find(params[:product_id])
      order.products.delete(product)
      order.compute_total
      order.counting_products
      redirect_to cart_path, notice: "Product removed successfuly"
  end

  def mercadopago
    order = Order.find(params[:order_id])
   
    require 'mercadopago'
    sdk = Mercadopago::SDK.new(ENV["MERCADOPAGO_ACCESS_TOKEN"])

    preference_data = {
      items: [
        {
          title: "Order no. #{order.id}",
          unit_price: order.total,
          quantity: 1
        }
      ],
      back_urls: {
        success: "https://afternoon-harbor-73328.herokuapp.com/payment-info",
        failure: "https://afternoon-harbor-73328.herokuapp.com/",
        pending: "https://afternoon-harbor-73328.herokuapp.com/"
      },
      auto_return: "approved",
    }
    preference_response = sdk.preference.create(preference_data)

    preference = preference_response[:response]
  
    @preference_id = preference['id']

    sandbox_init_point = preference["sandbox_init_point"]
    redirect_to sandbox_init_point
  end

  def payment_info
    @order = current_order
    status_param = params[:status]
    if status_param == "approved"
      created_payment = Payment.create(
                          status: status_param,
                          total: current_order.total,
                          merchant_order_id: params[:merchant_order_id],
                          order_id: current_order.id
                        )
      PaymentMailer.received_payment(current_user, created_payment).deliver_later
      current_order.compute_stock
      current_order.update_attribute(:state, 2)
      redirect_to orders_path, notice: "Payment processed successfully"
    else
     redirect_to cart_path, alert: "Failed payment process, please try again"
    end
  end

  private

  def params_token
    params[:token]
  end

end

app/views/carts/_cart.html.erb
<%= link_to "#{current_order.product_orders.size} products in the cart for a subtotal of #{current_order.subtotal}", carts_show_path%>

app/views/carts/_cart_item.html.erb
<% @product_orders.each do |product| %>

    <h3><%= product.product.title %></h3>
    <h5><%= product.product.unit_price %></h5>


    <%= form_for product, remote: true do |f| %>
        <%= f.hidden_field :product_id, :value => product.product.id %>
        <%= f.number_field :quantity, :value => product.quantity.to_i %>
        <%= f.submit "Update Card "%>
        <%= link_to "Remove Items", product_order_path(product), method: :delete, remote: true%>
    <% end %>
    <h2>Subtotal: <%= product.total %></h2>

<% end %>




<h3>Your current cart subtotal is <%= current_order.subtotal %></h3>

app/views/carts/show.html.erb
<div class="card">
    <div class="card-header bg-secondary text-light">
        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
        <a href="<%= products_path%>" class="btn btn-light btn-sm pull-right">Continue Shopping</a>
        <div class="clearfix"></div>
    </div>
    <div class="card-body">
      <% @order.products.each do |item| %>
        <div class="row">
            <div class="col-xs-2 col-md-2">
              <% if item.image.attached? %>
                <%= image_tag item.image.variant(resize: "75x50"), alt: "#{item.title}" %>
				      <% end %>
            </div>
            <div class="col-xs-4 col-md-6">
              <h4 class="product-name"><strong><%= item.title %></strong></h4><h4><small><%= item.description %></small></h4>
            </div>
            <div class="col-xs-6 col-md-4 row">
                <div class="col-xs-6 col-md-6 text-right" style="padding-top: 5px">
                  <h6><strong><%= number_to_currency(item.unit_price, strip_insignificant_zeros: true, delimiter: ".") %><span class="text-muted">x</span></strong></h6>
                </div>
                <div class="col-xs-4 col-md-4">
                  <%= item.get_quantity(@order)%>
                </div>
                <div class="col-xs-2 col-md-2">
                  <%= link_to remove_product_path(@order.id, item.id), method: :delete do  %>
                  <i class="far fa-trash-alt fa-2x"></i>
                  <% end %>
                </div>
            </div>
        </div>
        <hr>
      <% end %>

    </div>
    <div class="card-footer">
        <div class="pull-right" style="margin: 5px">
          Total: <%= number_to_currency(@order.total, strip_insignificant_zeros: true, delimiter: ".") %></b>
          <%= button_to "Pay with mercado pago", mercado_pago_path(@order.id), method: :get, class:"btn btn-primary btn-sm" %>
        </div>
    </div>
</div>

app/views/carts/show_antiguo.html.erb
<div class="card">
    <div class="card-header bg-dark text-light">
        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
        <a href="<%= products_path%>" class="btn btn-outline-info btn-sm pull-right">Continue Shopping</a>
        <div class="clearfix"></div>
    </div>
    <div class="card-body">
      <% @order.products.each do |item| %>
        <div class="row">
            <div class="col-xs-2 col-md-2">
                <img class="img-responsive" src="http://placehold.it/120x80" alt="prewiew">
            </div>
            <div class="col-xs-4 col-md-6">
              <h4 class="product-name"><strong><%= item.title %></strong></h4><h4><small><%= item.description %></small></h4>
            </div>
            <div class="col-xs-6 col-md-4 row">
                <div class="col-xs-6 col-md-6 text-right" style="padding-top: 5px">
                  <h6><strong><%= number_to_currency(item.unit_price, strip_insignificant_zeros: true, delimiter: ".") %><span class="text-muted">x</span></strong></h6>
                </div>
                <div class="col-xs-4 col-md-4">
                  <%= item.get_quantity(@order)%>
                </div>
                <div class="col-xs-2 col-md-2">
                  <%= link_to 'Remove product', remove_product_path(@order.id, item.id), method: :delete  %>
                </div>
            </div>
        </div>
        <hr>
      <% end %>

    </div>
    <div class="card-footer">
        <div class="pull-right" style="margin: 5px">
          Total: <%= number_to_currency(@order.total, strip_insignificant_zeros: true, delimiter: ".") %></b>
          <%= button_to "Pay with mercado pago", mercado_pago_path(@order.id), method: :get, class:"btn btn-info btn-sm" %>
        </div>
    </div>
</div>