config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :products do
    member do
      put 'like' => 'products#like'
    end
  end

  Rails.application.routes.draw do
    devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions',
      omniauth_callbacks: 'users/omniauth_callbacks'
    }
  end


  root to: "main#index"

  
  delete "users/:id", to: "users#destroy", as: "destroy_user"

  get "users_list", to: "main#users"
  get "product_list", to: "main#products"
  get "dashboard", to: "main#dashboard"
  get "/edit_role/:user_id", to: "main#edit_role", as: "edit_role"
  post "/edit_role/:user_id", to: "main#edit_role", as: "update_role"

  resource :cart, only: [:show, :update]
  delete 'cart/:order_id/remove_product/:product_id/', to: 'carts#remove_product', as: 'remove-product'
  get "cart/:order_id/mercado-pago", to: "carts#mercadopago", as: "mercado-pago"
  get "payment-info", to: "carts#payment_info"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  resourcify
  belongs_to :user
  has_many :product_orders, dependent: :destroy
  has_many :orders, through: :product_orders
  has_one_attached :image
  acts_as_votable
  
  validates :title, :stock, :unit_price, presence: true
  validates :description, length: {maximum: 500, too_long: "%#{count} exceeds the character limit."}
  validates :title, length: {maximum: 140, too_long: "%#{count} exceeds the character limit."}
  
  def get_quantity(order)
    self.product_orders.where(order_id: order.id).pluck(:quantity).first
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource
  before_action :set_product, only: %i[ show edit update destroy like ]
  before_action :authenticate_user!
  

  # GET /products or /products.json
  def index
    @products = Product.with_attached_image.all.order("created_at desc").page(params[:page]).per(16)
    @q = Product.includes(:user).ransack(params[:q])
    @products = @q.result(distinct: true).page(params[:page]).per(16)
  end

  # GET /products/1 or /products/1.json
  def show
    @products = Product.where(user_id: @product.user_id).limit(4)
  
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params.merge(user: current_user))

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def like
    if current_user.voted_for? @product
      @product.unliked_by current_user
    else
      @product.liked_by current_user
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :description, :stock, :unit_price, :user_id, :image)
    end
end

app/helpers/products_helper.rb
module ProductsHelper

end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Product image" %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :stock %>
    <%= form.number_field :stock %>
  </div>

  <div class="field">
    <%= form.label :unit_price %>
    <%= form.number_field :unit_price %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-outline-dark btn-sm" %>
  </div>
<% end %>

app/views/products/_like_link.html.erb
<% if current_user&.voted_for?(product) %>
  <% vote_text = capture do %>
    <i class="fas fa-heart fa-sm"></i> Unlike
  <% end %>
<% else %>
  <% vote_text = capture do %>
    <i class="far fa-heart fa-sm"></i> Like
  <% end %>
<% end %>

<%= link_to vote_text, like_product_path(product), method: :put, remote: :true, class: "like-product"  %>

app/views/products/_likes.html.erb
<%= pluralize(product.get_upvotes.size, 'Like') %>

app/views/products/edit.html.erb
<section class="page-section">
  <div class="container">
    <div class="about-heading-content">
      <div class="row">
        <div class="col-xl-9 col-lg-10 mx-auto">
          <div class="bg-faded rounded p-5">
            <h2 class="section-heading mb-4">
              <span class="section-heading-lower">Editing Product</span>
            </h2>
            <p>

              <%= render 'form', product: @product %>

              <%= link_to 'Show', @product, class: "btn btn-outline-dark btn-sm" %> 
              <%= link_to 'Back', products_path,  class: "btn btn-outline-dark btn-sm" %>
           </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section> 

app/views/products/index.html.erb
<section class="page-section cta">
  <div class="container">     
    <h2 class="section-heading mb-5 cta-inner bg-faded text-center rounded p-2">
      <span class="section-heading-lower">Goods & Merch</span>
    </h2>
    <div class="py-4 page-section cta-inner bg-faded ">
      <div class="d-grid gap-2 d-md-flex flex-row justify-content-md-end mt-2">
        <%= search_form_for @q do |f| %>
          <div class="input-group p-2 bd-highlight ">
            <%= f.search_field :title_or_user_name_cont, placeholder: "Search...", class: "form-control form-control-sm" %>
            <%= f.submit "Search", class: "btn btn-outline-dark btn-sm" %>
          </div>
        <% end %>

        <div class="input-group p-2 bd-highlight justify-content-md-end">
          <% if current_user.has_role?(:owner) || current_user.has_role?(:admin) %>
            <%= link_to new_product_path do %>
              <button class="btn btn-outline-dark btn-sm" type="button">Add more products</button>
            <% end %>
          <% end %>
          <button class="btn btn-outline-primary btn-sm" type="button">
          <%= sort_link @q, :unit_price do %>
         Sort by Price
          <% end %>
          </button>
        </div>
      </div>
      <p>
        <%= render 'shared/productlist' %>
      </p>
      <div class="pagination justify-content-center pagination-sm">
        <h4 class="mb-4 cta-inner bg-faded text-center rounded p-3">
          <span class="address" style="letter-spacing: 2px"><%= paginate @products %></span>
        </h4>
      </div>
    </div>
  </div>
</section>

app/views/products/like.js.erb
$("#like-count").html("<%= j render 'products/likes', product: @product %>");
$("#like-link").html("<%= j render 'products/like_link', product: @product %>");

app/views/products/new.html.erb
<section class="page-section">
  <div class="container">
    <div class="about-heading-content">
      <div class="row">
        <div class="col-xl-9 col-lg-10 mx-auto">
          <div class="bg-faded rounded p-5">
            <h2 class="section-heading mb-4">
              <span class="section-heading-lower">New Product</span>
            </h2>
            <p>
              <%= render 'form', product: @product %>
              
              <%= link_to 'Back', products_path,  class: "btn btn-outline-dark btn-sm" %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section> 

app/views/products/show.html.erb
<section class="pt-5">
  <div class="container px-4 px-lg-5 my-5">
    <div class="row gx-4 gx-lg-5 align-items-center">
      <div class="col-md-6">
        <%= image_tag @product.image.variant(resize: "600x700"), class: "card-img-top mb-5 mb-md-0", alt: "#{@product.title}" %>
      </div>
      <div class="intro-text p-5 bg-faded rounded col-md-6">
        <h2 class="section-heading mb-1">
          <span class="section-heading-upper"><%= @product.user.name %></span>
          <span class="section-heading-lower"><%= @product.title %></span>
        </h2>
        <div class="fs-5 mb-4">
          <span><%= number_to_currency(@product.unit_price, strip_insignificant_zeros: true, delimiter: ".") %></span>
        </div>
        <p class="fw-bold address mb-5">
          <%= @product.description %>
        </p>
        <ul class="list-unstyled list-hours mb-5 text-left">
          <li id="list-unstyled-item list-hours-item d-flex like-count"><%= render 'products/likes', product: @product %>
          <span id="ms-auto like-link"> | <%= render 'products/like_link', product: @product %></span></li>
        </ul>
        <div class="d-flex pt-4">
          <% if @product.stock > 0  %>
            <%= form_for :cart, url: cart_path, method: :put do |f| %>
              <%= f.hidden_field :product_id, value: @product.id %>
              <%= f.hidden_field :quantity, value: 1 %>
              <%= f.submit "Add to cart", class: "btn btn-outline-dark mt-auto" %>
            <% end %>
          <% else %>
            <%= button_tag "Out of Stock", disabled: true, class: "btn btn-outline-dark mt-auto"%>
          <% end %>
        </div>
        <% if product_owner(@product) %>
          <div class="d-grid gap-2 d-md-flex justify-content-md-end mt-5">
            <%= link_to edit_product_path(@product) do %>
              <button class="btn btn-outline-dark btn-sm" type="button">Edit product</button>
            <% end %>
            <%= link_to @product, method: :delete, data: {confirm: "Are you sure?"} do %>
              <button class="btn btn-outline-dark btn-sm" type="button">Delete product</button>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>
<section class="page-section cta d-none d-lg-block">
  <div class="container">     
    <h2 class="section-heading mb-4 cta-inner bg-faded text-center rounded p-2">
      <span class="section-heading-lower">Related Products</span>
    </h2>
    <p>
      <%= render 'shared/productlist' %>
    </p>
  </div>
</section>